# Generated by Django 5.0.4 on 2024-05-01 15:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('air_quality_aqi', models.IntegerField()),
                ('co2', models.FloatField()),
                ('voc', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.monitor')),
            ],
        ),
    ]
